# Code Generated by Sidekick is for learning and experimentation purposes only.
# Code Generated by Sidekick is for learning and experimentation purposes only.

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer


st.title("📊 Sentiment Analysis Dashboard")

# Sidebar
st.sidebar.header("About")
st.sidebar.info("This app analyzes the sentiment of text using TextBlob.")

# Main input
text_input = st.text_area("Enter text to analyze:", height=150)

if st.button("Analyze Sentiment"):
    if text_input:
        blob = TextBlob(text_input)
        polarity = blob.sentiment.polarity
        subjectivity = blob.sentiment.subjectivity
        
        # Determine sentiment
        if polarity > 0:
            sentiment = "Positive 😊"
            color = "green"
        elif polarity < 0:
            sentiment = "Negative 😞"
            color = "red"
        else:
            sentiment = "Neutral 😐"
            color = "gray"
        
        # Display results
        st.success(f"Sentiment: {sentiment}")
        
        col1, col2 = st.columns(2)
        with col1:
            st.metric("Polarity", f"{polarity:.2f}")
        with col2:
            st.metric("Subjectivity", f"{subjectivity:.2f}")
        
        # Visualization
        df = pd.DataFrame({
            'Metric': ['Polarity', 'Subjectivity'],
            'Score': [polarity, subjectivity]
        })
        
        fig = px.bar(df, x='Metric', y='Score', 
                     title='Sentiment Scores',
                     color='Metric')
        st.plotly_chart(fig)
    else:
        st.warning("Please enter some text to analyze!")
