# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import numpy as np
from wordcloud import WordCloud
import matplotlib.pyplot as plt
from collections import Counter
import re

# Page configuration
st.set_page_config(
    page_title="Sentiment Analysis Dashboard",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
    <style>
    .main {
        padding: 0rem 1rem;
    }
    .stMetric {
        background-color: #f0f2f6;
        padding: 15px;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .stMetric label {
        color: #31333F !important;
        font-weight: 600 !important;
        font-size: 0.9rem !important;
    }
    .stMetric [data-testid="stMetricValue"] {
        color: #0f1419 !important;
        font-size: 1.8rem !important;
        font-weight: 600 !important;
    }
    .stMetric [data-testid="stMetricDelta"] {
        color: #31333F !important;
    }
    </style>
""", unsafe_allow_html=True)


# Initialize VADER
@st.cache_resource
def get_analyzer():
    return SentimentIntensityAnalyzer()


analyzer = get_analyzer()


def analyze_sentiment(text):
    """Analyze sentiment using VADER"""
    if pd.isna(text) or text == '':
        return 0
    scores = analyzer.polarity_scores(str(text))
    return scores['compound']


def categorize_sentiment(score):
    """Categorize sentiment into Positive, Neutral, Negative"""
    if score >= 0.05:
        return 'Positive'
    elif score <= -0.05:
        return 'Negative'
    else:
        return 'Neutral'


def flag_issues(text, sentiment_score):
    """Identify comments that may need attention"""
    flags = []
    text_lower = str(text).lower()

    # Very negative sentiment
    if sentiment_score < -0.3:
        flags.append("🔴 Highly Negative")

    # Concern keywords
    concern_keywords = [
        'concern', 'worried', 'afraid', 'disappointed', 'frustrated',
        'angry', 'upset', 'unfair', 'problem', 'issue', 'broken',
        "doesn't work", 'not working', 'failed', 'failure'
    ]
    if any(keyword in text_lower for keyword in concern_keywords):
        flags.append("⚠️ Concern Expressed")

    # Urgent/critical indicators
    urgent_keywords = [
        'urgent', 'critical', 'immediately', 'asap', 'emergency',
        'need help', 'struggling', 'crisis'
    ]
    if any(keyword in text_lower for keyword in urgent_keywords):
        flags.append("🚨 Urgent")

    # Questions about leadership/direction
    leadership_keywords = [
        'leadership', 'direction', 'strategy', 'vision', 'clarity',
        'confused', 'unclear', "don't understand", 'transparency'
    ]
    if any(keyword in text_lower for keyword in leadership_keywords):
        flags.append("👥 Leadership/Direction")

    # Workload/burnout concerns
    workload_keywords = [
        'burnout', 'overwhelmed', 'too much work', 'overworked',
        'work-life balance', 'exhausted', 'stressed', 'workload'
    ]
    if any(keyword in text_lower for keyword in workload_keywords):
        flags.append("😰 Workload/Burnout")

    # Compensation/career concerns
    comp_keywords = [
        'pay', 'salary', 'compensation', 'promotion', 'career',
        'advancement', 'raise', 'bonus', 'underpaid'
    ]
    if any(keyword in text_lower for keyword in comp_keywords):
        flags.append("💰 Compensation/Career")

    return flags


@st.cache_data
def load_and_process_data(plc_file, allhands_meta_file, allhands_questions_file):
    """Load and process all uploaded data files"""
    dfs = []

    # Process PLC Meetings file
    if plc_file is not None:
        plc_df = pd.read_csv(plc_file)
        plc_df = plc_df.rename(columns={
            'Meeting Title': 'meeting_name',
            'Meeting Date': 'date',
            'Notes': 'text',
            'PLC Level': 'audience_level'
        })
        plc_df['meeting_type'] = 'PLC'
        dfs.append(plc_df)

    # Process All Hands data (JOIN metadata + questions)
    if allhands_meta_file is not None and allhands_questions_file is not None:
        ah_meta_df = pd.read_csv(allhands_meta_file)
        ah_q_df = pd.read_csv(allhands_questions_file)

        ah_combined = ah_q_df.merge(
            ah_meta_df,
            on='Webinar ID',
            how='left',
            suffixes=('_question', '_meta')
        )

        ah_combined = ah_combined.rename(columns={
            'Title': 'meeting_name',
            'Meeting Date_meta': 'date',
            'Questions': 'text',
            'Meeting Audience': 'audience_level'
        })
        ah_combined['meeting_type'] = 'All Hands'
        ah_combined = ah_combined[['meeting_name', 'date', 'text', 'audience_level', 'meeting_type']]

        st.sidebar.success(f"✅ All Hands (joined): {len(ah_combined)} records")
        dfs.append(ah_combined)

    elif allhands_questions_file is not None:
        ah_q_df = pd.read_csv(allhands_questions_file)
        ah_q_df = ah_q_df.rename(columns={
            'Topic': 'meeting_name',
            'Meeting Date': 'date',
            'Questions': 'text'
        })
        ah_q_df['audience_level'] = 'Unknown'
        ah_q_df['meeting_type'] = 'All Hands'

        st.sidebar.warning("⚠️ All Hands Questions uploaded without Metadata - audience info missing")
        dfs.append(ah_q_df)

    if len(dfs) > 0:
        df = pd.concat(dfs, ignore_index=True)

        df['sentiment_score'] = df['text'].apply(analyze_sentiment)
        df['sentiment_category'] = df['sentiment_score'].apply(categorize_sentiment)
        df['date'] = pd.to_datetime(df['date'], errors='coerce')

        df['flags'] = df.apply(
            lambda row: flag_issues(row['text'], row['sentiment_score']),
            axis=1
        )
        df['has_flags'] = df['flags'].apply(lambda x: len(x) > 0)

        return df

    return None


# Title
st.title("📊 Sentiment Analysis Dashboard")
st.markdown("### Analyze sentiment trends across PLC and All Hands meetings")
st.markdown("---")

# Sidebar for file uploads
st.sidebar.header("📁 Data Upload")
st.sidebar.markdown("Upload your sentiment data files below:")

plc_file = st.sidebar.file_uploader(
    "📋 PLC Meetings (plc_meetings.csv)",
    type=['csv'],
    key='plc'
)
allhands_meta_file = st.sidebar.file_uploader(
    "🎤 All Hands Metadata (allhands_metadata.csv)",
    type=['csv'],
    key='ah_meta'
)
allhands_questions_file = st.sidebar.file_uploader(
    "❓ All Hands Questions (allhands_questions.csv)",
    type=['csv'],
    key='ah_q'
)

# Process data if at least one file is uploaded
if plc_file is not None or allhands_meta_file is not None or allhands_questions_file is not None:
    with st.spinner('Loading and analyzing data...'):
        df = load_and_process_data(plc_file, allhands_meta_file, allhands_questions_file)

    if df is not None and len(df) > 0:
        # Show upload status
        st.sidebar.markdown("---")
        st.sidebar.markdown("### ✅ Upload Status:")

        if plc_file is not None:
            plc_count = len(df[df['meeting_type'] == 'PLC'])
            st.sidebar.success(f"✅ PLC: {plc_count} records")

        if allhands_meta_file is not None:
            ah_meta_count = len(df[df['meeting_type'] == 'All Hands'])
            st.sidebar.success(f"✅ All Hands Metadata: {ah_meta_count} records")

        if allhands_questions_file is not None:
            ah_q_count = len(df[df['meeting_type'] == 'All Hands'])
            st.sidebar.success(f"✅ All Hands Questions: {ah_q_count} records")

        st.sidebar.info(f"📊 Total: {len(df)} records")

        # Sidebar Filters
        st.sidebar.markdown("---")
        st.sidebar.header("🔍 Filters")

        # Meeting Name filter
        all_meetings = sorted(df['meeting_name'].dropna().unique().tolist())
        selected_meetings = st.sidebar.multiselect(
            "Meeting Name:",
            options=all_meetings,
            default=all_meetings,
            help="Select one or more meetings to analyze"
        )

        # Meeting Audience filter
        all_audiences = sorted(df['audience_level'].dropna().unique().tolist())
        selected_audiences = st.sidebar.multiselect(
            "Meeting Audience:",
            options=all_audiences,
            default=all_audiences,
            help="Select audience levels to include"
        )

        # Meeting type filter
        meeting_types = ['All'] + sorted(df['meeting_type'].dropna().unique().tolist())
        selected_meeting_type = st.sidebar.selectbox("Meeting Type:", meeting_types)

        # Sentiment filter
        sentiment_filter = st.sidebar.multiselect(
            "Sentiment Category:",
            ['Positive', 'Neutral', 'Negative'],
            default=['Positive', 'Neutral', 'Negative']
        )

        # Apply filters
        filtered_df = df.copy()

        if selected_meetings:
            filtered_df = filtered_df[filtered_df['meeting_name'].isin(selected_meetings)]

        if selected_audiences:
            filtered_df = filtered_df[filtered_df['audience_level'].isin(selected_audiences)]

        if selected_meeting_type != 'All':
            filtered_df = filtered_df[filtered_df['meeting_type'] == selected_meeting_type]

        if sentiment_filter:
            filtered_df = filtered_df[filtered_df['sentiment_category'].isin(sentiment_filter)]

        # Display filter info
        if len(filtered_df) < len(df):
            st.info(f"📌 Showing {len(filtered_df)} of {len(df)} records based on filters")

        # Key Metrics
        st.markdown("## 📈 Key Metrics")
        col1, col2, col3, col4, col5 = st.columns(5)

        with col1:
            st.metric("Total Comments", f"{len(filtered_df):,}")

        with col2:
            avg_sentiment = filtered_df['sentiment_score'].mean() if len(filtered_df) > 0 else 0
            st.metric("Avg Sentiment", f"{avg_sentiment:.3f}")

        with col3:
            positive_pct = (
                (filtered_df['sentiment_category'] == 'Positive').sum() / len(filtered_df) * 100
                if len(filtered_df) > 0 else 0
            )
            st.metric("Positive", f"{positive_pct:.1f}%")

        with col4:
            neutral_pct = (
                (filtered_df['sentiment_category'] == 'Neutral').sum() / len(filtered_df) * 100
                if len(filtered_df) > 0 else 0
            )
            st.metric("Neutral", f"{neutral_pct:.1f}%")

        with col5:
            negative_pct = (
                (filtered_df['sentiment_category'] == 'Negative').sum() / len(filtered_df) * 100
                if len(filtered_df) > 0 else 0
            )
            st.metric("Negative", f"{negative_pct:.1f}%")

        st.markdown("---")

        # Flagged Issues Section
        st.markdown("## 🚨 Issues Requiring Attention")

        flagged_df = filtered_df[filtered_df['has_flags']].copy()

        if len(flagged_df) > 0:
            col1, col2 = st.columns([1, 3])

            with col1:
                st.metric("Flagged Comments", f"{len(flagged_df):,}")
                flag_pct = len(flagged_df) / len(filtered_df) * 100 if len(filtered_df) > 0 else 0
                st.metric("% of Total", f"{flag_pct:.1f}%")

            with col2:
                all_flags = []
                for flags_list in flagged_df['flags']:
                    all_flags.extend(flags_list)

                flag_counts = pd.Series(all_flags).value_counts()
                st.write("**Flag Distribution:**")

                flag_cols = st.columns(min(3, len(flag_counts)))
                for idx, (flag_type, count) in enumerate(flag_counts.items()):
                    with flag_cols[idx % len(flag_cols)]:
                        st.metric(flag_type, f"{count:,}")

            st.markdown("---")
            st.markdown("### 📋 Flagged Comments Details")

            flag_type_filter = st.multiselect(
                "Filter by flag type:",
                options=sorted(flag_counts.index.tolist()),
                default=sorted(flag_counts.index.tolist()),
                key="flag_filter"
            )

            if flag_type_filter:
                display_df_flags = flagged_df[
                    flagged_df['flags'].apply(lambda x: any(flag in x for flag in flag_type_filter))
                ]
            else:
                display_df_flags = flagged_df

            display_df_flags = display_df_flags.sort_values('sentiment_score')

            st.write(f"Showing **{len(display_df_flags)}** flagged comments:")

            for idx, row in display_df_flags.iterrows():
                with st.expander(
                    f"**{row['meeting_name']}** | {', '.join(row['flags'])} | Sentiment: {row['sentiment_score']:.3f}",
                    expanded=False
                ):
                    detail_col1, detail_col2 = st.columns([2, 1])

                    with detail_col1:
                        st.markdown("**Comment:**")
                        st.write(row['text'])

                    with detail_col2:
                        st.markdown("**Details:**")
                        if pd.notna(row['date']):
                            st.write(f"📅 Date: {row['date'].strftime('%Y-%m-%d')}")
                        else:
                            st.write("📅 Date: Unknown")
                        st.write(f"👥 Audience: {row['audience_level']}")
                        st.write(f"📊 Meeting Type: {row['meeting_type']}")
                        st.write(f"😊 Sentiment: {row['sentiment_category']}")
                        st.write(f"📈 Score: {row['sentiment_score']:.3f}")
                        st.markdown("**Flags:**")
                        for flag in row['flags']:
                            st.write(f"• {flag}")
        else:
            st.success("✅ No issues flagged in the current filtered data!")

        # Visualizations
        st.markdown("## 📊 Visualizations")

        # Row 1: Sentiment Distribution and Meeting Type
        col1, col2 = st.columns(2)

        with col1:
            st.markdown("### Sentiment Distribution")
            if len(filtered_df) > 0:
                sentiment_counts = filtered_df['sentiment_category'].value_counts()
                fig1 = px.pie(
                    values=sentiment_counts.values,
                    names=sentiment_counts.index,
                    color=sentiment_counts.index,
                    color_discrete_map={
                        'Positive': '#00CC96',
                        'Neutral': '#FFA15A',
                        'Negative': '#EF553B'
                    },
                    hole=0.4
                )
                fig1.update_traces(textposition='inside', textinfo='percent+label')
                fig1.update_layout(showlegend=True, height=400)
                st.plotly_chart(fig1, use_container_width=True)
            else:
                st.info("No data available")

        with col2:
            st.markdown("### Average Sentiment by Meeting Type")
            if len(filtered_df) > 0:
                meeting_sentiment = (
                    filtered_df.groupby('meeting_type')['sentiment_score']
                    .mean()
                    .reset_index()
                    .sort_values('sentiment_score', ascending=False)
                )

                fig2 = px.bar(
                    meeting_sentiment,
                    x='meeting_type',
                    y='sentiment_score',
                    color='sentiment_score',
                    color_continuous_scale=['#EF553B', '#FFA15A', '#00CC96'],
                    text='sentiment_score'
                )
                fig2.update_traces(texttemplate='%{text:.3f}', textposition='outside')
                fig2.update_layout(
                    showlegend=False,
                    height=400,
                    yaxis_title="Average Sentiment Score",
                    xaxis_title="Meeting Type"
                )
                fig2.add_hline(y=0, line_dash="dash", line_color="gray")
                st.plotly_chart(fig2, use_container_width=True)
            else:
                st.info("No data available")

        # Row 2: Sentiment Over Time
        st.markdown("### 📈 Sentiment Trend Over Time")

        if len(filtered_df) > 0:
            daily_sentiment = (
                filtered_df.groupby('date', dropna=True)['sentiment_score']
                .mean()
                .reset_index()
                .sort_values('date')
            )

            if len(daily_sentiment) > 0:
                fig3 = px.line(
                    daily_sentiment,
                    x='date',
                    y='sentiment_score',
                    markers=True
                )
                fig3.update_layout(
                    height=400,
                    xaxis_title="Date",
                    yaxis_title="Avg Sentiment Score"
                )
                fig3.add_hline(y=0, line_dash="dash", line_color="gray")
                st.plotly_chart(fig3, use_container_width=True)
            else:
                st.info("No date-based trend data available")
        else:
            st.info("No data available")

        # Row 3: Audience Level and Meeting Breakdown
        col1, col2 = st.columns(2)

        with col1:
            st.markdown("### Sentiment by Meeting Audience")
            if len(filtered_df) > 0 and filtered_df['audience_level'].notna().any():
                audience_sentiment = (
                    filtered_df.dropna(subset=['audience_level'])
                    .groupby('audience_level')['sentiment_score']
                    .mean()
                    .reset_index()
                    .sort_values('sentiment_score', ascending=True)
                )

                fig4 = px.bar(
                    audience_sentiment,
                    y='audience_level',
                    x='sentiment_score',
                    orientation='h',
                    color='sentiment_score',
                    color_continuous_scale=['#EF553B', '#FFA15A', '#00CC96'],
                    text='sentiment_score'
                )
                fig4.update_traces(texttemplate='%{text:.3f}', textposition='outside')
                fig4.update_layout(
                    showlegend=False,
                    height=400,
                    xaxis_title="Average Sentiment Score",
                    yaxis_title="Meeting Audience"
                )
                fig4.add_vline(x=0, line_dash="dash", line_color="gray")
                st.plotly_chart(fig4, use_container_width=True)
            else:
                st.info("No audience data available")

        with col2:
            st.markdown("### Comments by Meeting")
            if len(filtered_df) > 0:
                meeting_counts = filtered_df['meeting_name'].value_counts().head(10).reset_index()
                meeting_counts.columns = ['meeting_name', 'count']

                fig5 = px.bar(
                    meeting_counts,
                    x='count',
                    y='meeting_name',
                    orientation='h',
                    color='count',
                    color_continuous_scale='Blues'
                )
                fig5.update_layout(
                    showlegend=False,
                    height=400,
                    xaxis_title="Number of Comments",
                    yaxis_title="Meeting Name"
                )
                st.plotly_chart(fig5, use_container_width=True)
            else:
                st.info("No data available")

        # Word Clouds Section
        st.markdown("---")
        st.markdown("## ☁️ Word Clouds")

        col1, col2 = st.columns(2)

        with col1:
            st.markdown("### Positive Comments")
            positive_text = ' '.join(
                filtered_df[filtered_df['sentiment_category'] == 'Positive']['text'].astype(str)
            )
            if positive_text.strip() and len(positive_text) > 10:
                wordcloud_pos = WordCloud(
                    width=800,
                    height=400,
                    background_color='white',
                    colormap='Greens',
                    max_words=50
                ).generate(positive_text)
                fig, ax = plt.subplots(figsize=(10, 5))
                ax.imshow(wordcloud_pos, interpolation='bilinear')
                ax.axis('off')
                st.pyplot(fig)
            else:
                st.info("No positive comments available")

        with col2:
            st.markdown("### Negative Comments")
            negative_text = ' '.join(
                filtered_df[filtered_df['sentiment_category'] == 'Negative']['text'].astype(str)
            )
            if negative_text.strip() and len(negative_text) > 10:
                wordcloud_neg = WordCloud(
                    width=800,
                    height=400,
                    background_color='white',
                    colormap='Reds',
                    max_words=50
                ).generate(negative_text)
                fig, ax = plt.subplots(figsize=(10, 5))
                ax.imshow(wordcloud_neg, interpolation='bilinear')
                ax.axis('off')
                st.pyplot(fig)
            else:
                st.info("No negative comments available")

        # Top Comments Section
        st.markdown("---")
        st.markdown("## 💬 Notable Comments")

        col1, col2 = st.columns(2)

        with col1:
            st.markdown("### 💚 Top 5 Most Positive Comments")
            if len(filtered_df) > 0:
                top_positive = filtered_df.nlargest(
                    5,
                    'sentiment_score'
                )[['date', 'meeting_name', 'meeting_type', 'audience_level', 'text', 'sentiment_score']]

                for idx, row in top_positive.iterrows():
                    date_str = row['date'].strftime('%Y-%m-%d') if pd.notna(row['date']) else "Unknown"
                    st.success(
                        f"**{row['meeting_name']}** ({row['meeting_type']}) | "
                        f"{row['audience_level']} | {date_str}"
                    )
                    st.write(f"**Score:** {row['sentiment_score']:.3f}")
                    st.write(f"_{row['text']}_")
                    st.markdown("---")
            else:
                st.info("No positive comments")

        with col2:
            st.markdown("### ❤️ Top 5 Most Negative Comments")
            if len(filtered_df) > 0:
                top_negative = filtered_df.nsmallest(
                    5,
                    'sentiment_score'
                )[['date', 'meeting_name', 'meeting_type', 'audience_level', 'text', 'sentiment_score']]

                for idx, row in top_negative.iterrows():
                    date_str = row['date'].strftime('%Y-%m-%d') if pd.notna(row['date']) else "Unknown"
                    st.error(
                        f"**{row['meeting_name']}** ({row['meeting_type']}) | "
                        f"{row['audience_level']} | {date_str}"
                    )
                    st.write(f"**Score:** {row['sentiment_score']:.3f}")
                    st.write(f"_{row['text']}_")
                    st.markdown("---")
            else:
                st.info("No negative comments")

        # Data Table Section
        st.markdown("---")
        st.markdown("## 📋 Detailed Data View")

        if len(filtered_df) > 0:
            sort_col = st.selectbox(
                "Sort by:",
                ['date', 'sentiment_score', 'meeting_name', 'meeting_type', 'audience_level'],
                index=1
            )
            sort_order = st.radio("Order:", ['Descending', 'Ascending'], horizontal=True)

            display_df = filtered_df[
                ['date', 'meeting_name', 'meeting_type', 'audience_level', 'text', 'sentiment_score', 'sentiment_category']
            ].sort_values(sort_col, ascending=(sort_order == 'Ascending')).copy()

            display_df['date'] = display_df['date'].dt.strftime('%Y-%m-%d')

            st.dataframe(display_df, use_container_width=True, height=400)

            csv = display_df.to_csv(index=False)
            st.download_button(
                label="📥 Download Filtered Data as CSV",
                data=csv,
                file_name=f"sentiment_analysis_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv",
                mime="text/csv"
            )
        else:
            st.info("No data available")

    else:
        st.error("❌ No data could be loaded from the uploaded files. Please check your CSV format.")

else:
    # Welcome screen when no files are uploaded
    st.info("👆 Please upload at least one CSV file to begin sentiment analysis")

    st.markdown("### 📝 Expected CSV Format:")
    st.markdown("""
    Your CSV files should contain these columns:

    | Column | Description | Example |
    |--------|-------------|---------|
    | **Meeting Title** | Name of meeting | January PLC |
    | **Meeting Date** | Date of meeting | 2024-01-15 |
    | **Notes** | Feedback/comments | Great meeting... |
    | **PLC Level** | Practitioner level | SM, M, SC, All |
    """)

    st.markdown("### ✨ Dashboard Features:")
    st.markdown("""
    - **Sentiment Analysis**: Automatic sentiment scoring using VADER
    - **Multi-file Support**: Upload PLC meetings, All Hands metadata, and All Hands questions
    - **Interactive Filters**: Filter by meeting name, audience, and meeting type
    - **Rich Visualizations**: Charts, graphs, and word clouds
    - **Top Comments**: See most positive and negative feedback
    - **Data Export**: Download filtered results
    """)

st.markdown("---")
st.markdown("*Powered by VADER Sentiment Analysis | Built with Streamlit*")